blank_issues_enabled: true
contact_links:
  - name: Developer Documentation
    url: https://h-ntai.github.io/schlussstrich
    about: Dokumentation & Ratschläge bezüglich Ahmads Discord Server.
  - name: Community Server
    url: https://discord.gg/n4bhteN9YD
    about: Hast du Fragen? Kontaktiere mich hier!
